{% set version = "2.46.2" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}
{% set abi_version = "1.4" %}

package:
  name: pangomm
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/pangomm/{{ major_minor }}/pangomm-{{ version }}.tar.xz
  sha256: 57442ab4dc043877bfe3839915731ab2d693fc6634a71614422fb530c9eaa6f4

build:
  number: 0
  run_exports:
    - pangomm-{{ abi_version }} >={{ version }}

outputs:
  - name: pangomm-{{ abi_version }}
    script: build_pangomm.sh   # [unix]
    script: build_pangomm.bat  # [win]
    build:
      run_exports:
        - pangomm-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - pkg-config
        - meson
        - ninja
      host:
        - cairomm-1.0 >=1.2.2
        - pango >=1.41.0
        - glibmm-2.4 >=2.48.0
        - glib
      run_constrained:
        - pangomm {{ version }}
    test:
      requires:
        - pkg-config
        - glib
      commands:
        - test -f ${PREFIX}/lib/libpangomm-{{ abi_version }}${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_BIN%\\pangomm-vc142-{{ abi_version }}-1.dll exit 1  # [win]
        - pkg-config --cflags --libs pangomm-{{ abi_version }}
        - pkg-config --exact-version {{ version }} pangomm-{{ abi_version }}

  - name: pangomm
    requirements:
      run:
        - pangomm-{{ abi_version }}  {{ version }}
    test:
      requires:
        - pkg-config
      commands:
        - pkg-config --cflags --libs pangomm-{{ abi_version }}
        - pkg-config --exact-version {{ version }} pangomm-{{ abi_version }}

about:
  home: https://developer.gnome.org/pangomm/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: "C++ bindings for pango"
  dev_url: https://gitlab.gnome.org/GNOME/pangomm

extra:
  recipe-maintainers:
    - isuruf
    - tschoonj
