{% set version = "2.50.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}
{% set abi_version = "2.48" %}

package:
  name: pangomm
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/pangomm/{{ major_minor }}/pangomm-{{ version }}.tar.xz
  sha256: a27aa77e017b9afce9e751d85bd1cf890abbb3a58bf59d0fac917eef82db3b5b

build:
  number: 0
  run_exports:
    - pangomm-{{ abi_version }} >={{ version }}

outputs:
  - name: pangomm-{{ abi_version }}
    script: build_pangomm.sh  # [unix]
    script: build_pangomm.bat  # [win]
    build:
      run_exports:
        - pangomm-{{ abi_version }} >={{ version }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - pkg-config
        - meson
        - ninja
      host:
        - cairomm-1.16
        - pango
        - glibmm-2.68
        - glib
        - sigcpp-3.0
      run_constrained:
        - pangomm {{ version }}
    test:
      requires:
        - pkg-config
        - glib
      commands:
        - test -f ${PREFIX}/lib/libpangomm-{{ abi_version }}${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_BIN%\\pangomm-vc142-{{ abi_version }}-1.dll exit 1  # [win]
        - pkg-config --cflags --libs pangomm-{{ abi_version }}
        - pkg-config --exact-version {{ version }} pangomm-{{ abi_version }}

  - name: pangomm
    requirements:
      run:
        - pangomm-{{ abi_version }}  {{ version }}
    test:
      requires:
        - pkg-config
      commands:
        - pkg-config --cflags --libs pangomm-{{ abi_version }}
        - pkg-config --exact-version {{ version }} pangomm-{{ abi_version }}

about:
  home: https://developer.gnome.org/pangomm/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: C++ bindings for pango
  dev_url: https://gitlab.gnome.org/GNOME/pangomm

extra:
  recipe-maintainers:
    - isuruf
    - tschoonj
